from .nodes import NODE_CLASS_MAPPINGS as MAIN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MAIN_DISPLAY_MAPPINGS
from .test_counter import NODE_CLASS_MAPPINGS as TEST_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEST_DISPLAY_MAPPINGS
from .ls_node import LS_NODE_CLASS_MAPPINGS, LS_NODE_DISPLAY_NAME_MAPPINGS

# 全てのノードを含める
NODE_CLASS_MAPPINGS = {
    **MAIN_MAPPINGS,
    **TEST_MAPPINGS,
    **LS_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MAIN_DISPLAY_MAPPINGS,
    **TEST_DISPLAY_MAPPINGS,
    **LS_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]